### PR TITLE
Declare DbSet as virtual

### PR DESCRIPTION
**Pull request by vanillajonathan**
ASP.NET Core Identity [`IdentityDbContext.cs`](https://github.com/dotnet/aspnetcore/blob/main/src/Identity/EntityFrameworkCore/src/IdentityDbContext.cs) declare the `DbSet`'s as virtual.

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@damienbod ping!

**Comment by vanillajonathan** [comment]
@damienbod ping!

**Comment by vanillajonathan** [comment]
@damienbod merge!

**Comment by damienbod** [comment]
Thanks for the PR. We don't need virtual here. Greetings Damien

**Pull request closed without merging**
