### PR TITLE
Add documentation for the Id property

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@damienbod ping!

**Comment by damienbod** [comment]
Hi @vanillajonathan Thanks for the PR, I don't see what value this adds, I can already see that the property is an Id

**Comment by vanillajonathan** [comment]
This clarifies that the id is used as the primary key. The comment is identical to the one in the `IdentityUser` class in aspnetcore.

https://github.com/dotnet/aspnetcore/blob/1864aa518bbf1f6f9d1c0264e897a4b71a826d97/src/Identity/Extensions.Stores/src/IdentityUser.cs#L58-L62

**Comment by vanillajonathan** [comment]
@damienbod merge!

**Pull request merged**
